### ISSUE TITLE
Suggestion: Skill animation time / Cast time

### ISSUE THREAD

**Issue by Failyn** [BarutSRB/LA_Overlay#2]
Skill buff time bar does not accurately represent the ingame buff duration. Suggestion would be to add an extra argument to skills to add before the green bar starts ticking.

from: Skill("Example_Skill_Name", Cooldown, Buff duration)
to: Skill("Example_Skill_Name", Cooldown, Buff duration, Cast time)

For example Heavenly tune has about .5 seconds delay before buff is applied while Sonic Vibration needs almost a full second to resolve and start providing the buff.

Swiftness has impact on animation speed so perhaps a list can be kept with skills at 0 swiftness and then automatically calculated with swiftness. Spirit Absorption can increase this speed by up to 15% as well.

If/When more classes get implemented there is also a consideration for charging skills / holding skills and their speedups with relevant engraving.

Thanks for the work sofar!

**Comment by BarutSRB** [comment]
Thanks for your feedback. Integrating cast time into the skill function is a great idea. It will definitely show more accurately the actual buff timings for skills like Sonic Vibration or Harp.

It does present a challenge due to too many variables like swiftness and SA, not sure if there is already some formula for this that someone from the community did. A comprehensive list of skills with their cast times at 0 or certain swiftness without SA would be great. Hopefully, someone in the community can compile this data, which would be a huge help in adapting this into the overlay.

**Comment by BarutSRB** [comment]
I added cast times per skill that can be adjusted in settings.py
